### ISSUE TITLE
iOS default project has missing fonts

### ISSUE THREAD

**Issue by rumax** [muneneevans/themeable-react-native#1]
Trying to run the iOS default project with no changes leads to the error:

![screen shot 2019-02-26 at 14 36 19](https://user-images.githubusercontent.com/2707180/53416519-f7377400-39d3-11e9-95ab-52d3607a39d4.png)

**Comment by muneneevans** [comment]
You need to run 
`react-native link`
To copy the fonts to the native assets.

**Comment by rumax** [comment]
Hi @muneneevans,

I'm trying `react-native link`, but nothing happens:

```
$ react-native link
$ git status 
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   package-lock.json
```

Where are these fonts located? Are you missing `rnpm` in `package.json`?

**Comment by muneneevans** [comment]
My apologies. I had not included the font files.
I have updated the theme to use another font from google fonts.

I am also unable to test on IOS at the moment. So please Confirm for me, for the sake of others who will try on ios

**Comment by rumax** [comment]
👍
Now it works 💪

**Comment by rumax** [comment]
![screen shot 2019-02-27 at 08 37 33](https://user-images.githubusercontent.com/2707180/53473568-01588180-3a6b-11e9-9649-9e4d8f303b64.png)

Is it also expected result?

**Comment by muneneevans** [comment]
Rumax. Sorry, I was not notified about this comment
I have not tested it on IOS. Im open to any pull request about this issue
